#!/usr/bin/env python

import rospy
from std_msgs.msg import String
from std_msgs.msg import Float32
import time

CoordList = []


TaskPub = rospy.Publisher('TaskComplete', String, queue_size=10)         #intialise rostopic to indicate when task is completed

#store all the messages coming from the GUI
def storeCoord(data):
    Coord = float(data.data)
    CoordList.append(Coord)
    print(CoordList)
    return



if __name__ == '__main__':

    rospy.init_node('listener', anonymous=True)
    rospy.Subscriber('MATLAB', String, storeCoord)                          #make the subscriber for the MATLAB Coordinates
    
    while not rospy.is_shutdown():


        if CoordList:         #If the GUIList has items to look for
            CoordX = CoordList[0]             #X co-ordinate
            CoordY = CoordList[1]             #Y co-ordinate
            CoordZ = CoordList[2]             #Z co-ordinate


            del CoordList[0]                  #Delete the item off the wanted list
            del CoordList[0]
            del CoordList[0]
            print("coordinates deleted")

            #do arm stuff here: go to object and put in bin

            str1 = "task completed"
            TaskPub.publish(str1)

                

  
        rospy.sleep(0.5)
